In [1]:
import pandas as pd

# Load your dataset
df = pd.read_csv("../data/updated.csv")

In [2]:
df_clean = df.copy()
df_clean.drop(columns=["Unnamed: 0"], inplace = True)
df_clean.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607_x,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,11:30,11:45,4,0,2,3,3,0.0,1,3,24.0
1,0xb379_x,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,19:45,19:50,3,1,2,3,4,1.0,1,1,33.0
2,0x20f7_x,BANGRES18DEL01,37,4.4,12.913041,77.683237,12.953041,77.723237,13:50,13:55,6,0,0,0,3,2.0,1,1,42.0
3,0x7804_x,HYDRES13DEL02,28,4.9,17.431477,78.400350,17.451477,78.420350,10:60,11:15,2,2,1,2,4,1.0,1,3,19.0
4,0x7faf_x,RANCHIRES07DEL01,37,4.6,23.359407,85.325055,23.429407,85.395055,23:50,23:60,3,2,0,2,3,1.0,1,1,25.0

In [3]:
print("Before:", df_clean.shape)
df_clean.drop_duplicates(inplace = True)
print("After:", df_clean.shape)

Before: (2442, 19)
After: (2441, 19)

In [4]:
df_clean[df_clean["Delivery_person_Age"]==0]

median_age = df_clean.loc[
    df_clean["Delivery_person_Age"] > 0,
    "Delivery_person_Age"
].median()

df_clean.loc[
    df_clean["Delivery_person_Age"] == 0,
    "Delivery_person_Age"
] = median_age

df_clean["Delivery_person_Age"].describe()

count    2441.000000
mean       29.549775
std         5.698296
min        20.000000
25%        25.000000
50%        30.000000
75%        34.000000
max        50.000000
Name: Delivery_person_Age, dtype: float64

In [5]:
import numpy as np

df_clean.loc[
    df_clean["Delivery_person_Ratings"] > 5,
    "Delivery_person_Ratings"
] = np.nan

In [6]:
median_rating = df_clean["Delivery_person_Ratings"].median()

df_clean["Delivery_person_Ratings"].fillna(
    median_rating,
    inplace=True
)

C:\Users\Saurabh Choudhary\AppData\Local\Temp\ipykernel_16980\2657596210.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Delivery_person_Ratings"].fillna(

0       4.9
1       4.5
2       4.4
3       4.9
4       4.6
       ...
2436    4.7
2437    4.8
2438    5.0
2439    4.6
2441    4.9
Name: Delivery_person_Ratings, Length: 2441, dtype: float64

In [7]:
df_clean["multiple_deliveries"].value_counts(dropna=False)

mode_delivery = df_clean["multiple_deliveries"].mode()[0]

df_clean["multiple_deliveries"].fillna(
    mode_delivery,
    inplace=True
)

C:\Users\Saurabh Choudhary\AppData\Local\Temp\ipykernel_16980\280139745.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["multiple_deliveries"].fillna(

0       0.0
1       1.0
2       2.0
3       1.0
4       1.0
       ...
2436    0.0
2437    1.0
2438    1.0
2439    1.0
2441    0.0
Name: multiple_deliveries, Length: 2441, dtype: float64

In [8]:
df_clean[df_clean["Time_Orderd"].isnull()]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
24,0x6192,RANCHIRES010DEL03,30,NaN,23.354422,85.332900,23.384422,85.362900,NaN,19:15,4,3,1,0,4,0.0,1,1,15.0
85,0xd0d0,KNPRES13DEL01,30,NaN,26.481547,80.299775,26.551547,80.369775,NaN,19:35,2,1,1,1,4,1.0,1,1,38.0
115,0x18b9,RANCHIRES19DEL03,30,NaN,23.333017,85.317200,23.393017,85.377200,NaN,24:10,7,5,2,2,3,1.0,1,3,12.0
186,0x644,BANGRES04DEL02,30,NaN,12.980410,77.640489,13.060410,77.720489,NaN,20:40,4,1,0,2,3,1.0,1,1,31.0
188,0x52c,PUNERES14DEL02,30,NaN,18.516216,73.842527,18.646216,73.972527,NaN,18:30,7,5,1,1,3,1.0,1,1,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2232,0x6ec,MYSRES11DEL01,30,NaN,12.323225,76.630028,12.433225,76.740028,NaN,23:45,0,2,2,1,3,0.0,1,1,30.0
2286,0x1087,HYDRES14DEL01,30,NaN,17.426228,78.407495,17.436228,78.417495,NaN,10:50,6,2,2,3,3,1.0,1,3,15.0
2295,0x4b0,HYDRES18DEL02,30,NaN,-17.450851,-78.379347,17.500851,78.429347,NaN,21:15,2,1,2,0,4,1.0,1,1,25.0
2315,0x726,CHENRES19DEL03,30,NaN,12.986047,80.218114,13.076047,80.308114,NaN,21:50,4,1,2,1,4,0.0,1,1,19.0
2357,0x741,VADRES07DEL01,30,NaN,0.000000,0.000000,0.040000,0.040000,NaN,13:35,7,5,3,0,3,0.0,1,3,21.0

In [9]:
df_clean = df_clean.dropna(subset=["Time_Orderd"])

In [10]:
df_clean.isnull().sum()

ID                              0
Delivery_person_ID              0
Delivery_person_Age             0
Delivery_person_Ratings        10
Restaurant_latitude             0
Restaurant_longitude            0
Delivery_location_latitude      0
Delivery_location_longitude     0
Time_Orderd                     0
Time_Order_picked               0
Weatherconditions               0
Road_traffic_density            0
Vehicle_condition               0
Type_of_order                   0
Type_of_vehicle                 0
multiple_deliveries            52
Festival                        0
City                            0
Time_taken(min)                 0
dtype: int64

In [11]:
print(df_clean["Delivery_person_Ratings"].isna().sum())
print(df_clean["multiple_deliveries"].isna().sum())

10
52

In [12]:
print(df_clean["Delivery_person_Ratings"].unique())
print(df_clean["multiple_deliveries"].unique())

[4.9 4.5 4.4 4.6 4.7 4.8 5.  4.2 4.3 3.9 nan 4.1 4.  3.4 3.5 3.6 3.7 3.8
 3.3 3.2 2.8 2.5 2.9 3. ]
[ 0.  1.  2. nan  3.]

In [13]:
median_rating = df_clean["Delivery_person_Ratings"].median()

df_clean["Delivery_person_Ratings"] = (
    df_clean["Delivery_person_Ratings"]
    .fillna(median_rating)
)

In [14]:
df_clean["Delivery_person_Ratings"].isna().sum()

np.int64(0)

In [15]:
mode_delivery = df_clean["multiple_deliveries"].mode()[0]

df_clean["multiple_deliveries"] = (
    df_clean["multiple_deliveries"]
    .fillna(mode_delivery)
)

In [16]:
df_clean["multiple_deliveries"].isna().sum()

np.int64(0)

In [17]:
df_clean.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [18]:
print(df_clean.shape)

(2352, 19)

In [19]:
df_clean.to_csv(
    "../data/food_delivery_clean.csv",
    index=False
)